from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
from reportlab.lib.units import inch

styles = getSampleStyleSheet()

title = styles["Title"]
title.alignment = TA_CENTER

heading = styles["Heading1"]
body = styles["BodyText"]


def section(story, heading_text, body_text):
    story.append(Paragraph(heading_text, heading))
    story.append(Spacer(1, 0.12 * inch))
    story.append(Paragraph(str(body_text), body))
    story.append(Spacer(1, 0.25 * inch))


def generate_pdf(report):

    pdf = SimpleDocTemplate(
        "startup_report.pdf",
        rightMargin=35,
        leftMargin=35,
        topMargin=35,
        bottomMargin=35,
    )

    story = []

    # ---------------- Cover ---------------- #

    story.append(Paragraph("🚀 Startup Copilot", title))

    story.append(
        Paragraph(
            "<b>AI Generated Business Report</b>",
            styles["Heading2"],
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    story.append(
        Paragraph(
            f"<b>Startup Idea:</b> {report.get('idea', 'N/A')}",
            styles["Heading2"],
        )
    )

    story.append(Spacer(1, 0.35 * inch))

    # ---------------- Score ---------------- #

    story.append(Paragraph("⭐ Startup Score", heading))

    score_table = Table(
        [
            ["Score", str(report.get("startup_score", "N/A")) + "/100"],
            [
                "Recommendation",
                report.get("recommendation", "Not Available"),
            ],
        ],
        colWidths=[140, 320],
    )

    score_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("BOX", (0, 0), (-1, -1), 1, colors.black),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
            ]
        )
    )

    story.append(score_table)
    story.append(Spacer(1, 0.35 * inch))

    # ---------------- Report ---------------- #

    section(
        story,
        "📋 Executive Summary",
        report.get("summary", ""),
    )

    section(
        story,
        "📊 Market Analysis",
        report.get("market_analysis", ""),
    )

    section(
        story,
        "🏢 Competitor Analysis",
        report.get("competitor_analysis", ""),
    )

    section(
        story,
        "💰 Financial Plan",
        report.get("finance_plan", ""),
    )

    section(
        story,
        "📦 Product Strategy",
        report.get("product_strategy", ""),
    )

    section(
        story,
        "📢 Marketing Strategy",
        report.get("marketing_strategy", ""),
    )

    story.append(Spacer(1, 0.5 * inch))

    story.append(
        Paragraph(
            "<b>Generated by Startup Copilot</b>",
            styles["Heading2"],
        )
    )

    story.append(
        Paragraph(
            "React • FastAPI • LangGraph • Gemini • Firebase",
            body,
        )
    )

    pdf.build(story)

    return "startup_report.pdf"